## Zadanie: Oczyszczanie, walidacja i analiza danych osobowych oraz finansowych  


Otrzymujesz plik CSV zawierający dane osobowe oraz informacje o rocznych zarobkach. Dane zostały celowo zanieczyszczone błędami, aby odwzorować rzeczywiste problemy spotykane w pracy z danymi. Twoim zadaniem jest przygotowanie poprawnego, ujednoliconego i gotowego do analizy zbioru danych, a następnie wykonanie kilku analiz statystycznych.

### Wstępna analiza

- Zaimportuj wymagane biblioteki,
- Załaduj dane do obiektu typu DataFrame,
- Wypisz 5 kolejnych wierszy,
- Przeprowadź wstępną analizę danych za pomocą odpowiednich funkcji.

In [1]:
# import wymaganych bibliotek
import pandas as pd

In [2]:
# załadowanie pliku z danymi (dane_pracownicy.csv) do DataFrame
df = pd.read_csv('dane_pracownicy.csv',sep = ';', encoding='utf-8')

In [ ]:
# wypisz 5 pierwszych wierszy DataFrame
print(df.head())

In [ ]:
# analiza danych
df.describe()

In [ ]:
# analiza danych
df.info()

### Oczyszczanie danych

W pliku znajdują się kolumny:

- Id – unikalny identyfikator (niepotrzebny w analizie)
- imie
- nazwisko (również dwuczłonowe)
- PESEL (losowe cyfry)
- roczne_zarobki – kwota + waluta (np. „12345.67 PLN”, „9876,50 EUR”, „45000 USD”). Mogą znajdować się również kwoty bez walut

Dane zawierają błędy, które należy usunąć lub poprawić.

**Wymagane operacje:**  
- Usunięcie zbędnych danych
    - Usuń całą kolumnę Id.
    - Usuń rekordy, w których pole roczne_zarobki jest puste.

**Czyszczenie pól tekstowych:**
- Usuń niepotrzebne spacje na początku i końcu pól imie i nazwisko.
- Dostosuj wielkość liter: imię i nazwisko powinny zaczynać się wielką literą, pozostałe litery małe. Uwaga na nazwiska dwuczłonowe

**Walidacja numeru PESEL**
- Sprawdź, czy PESEL ma dokładnie 11 znaków. Jeśli PESEL jest niepoprawny → ustaw wartość NULL. Nie zwracaj uwagi na poprawność cyfr w numerze PESEL, obecnie są to wartości losowe, nie zawierają sensownych danych

In [3]:
kopia = df

In [4]:
# usunięcie zbędnej kolumny "id" z DataFrame
df = kopia
# df = df[['imie','nazwisko','PESEL','roczne_zarobki']]
df = df.drop(columns=['Id'], axis=1)
df

             imie          nazwisko        PESEL roczne_zarobki
0           anna         wiśniewski  60457830049  108834.73 USD
1             ewa      Lewandowski   76126262394  114301.11 USD
2           Paweł  WIŚNIEWSKA-NOWAK  18320244397       77021.21
3           KAROL       Lewandowski  45539418997  141116.51 USD
4          OSKAR             Mazur   11623970390   32817.31 EUR
...           ...               ...          ...            ...
49995        anna            Mazur   60969323785  163674.92 USD
49996      Julia     Zielony-Biały   86715437834   87930.15 PLN
49997       Julia             Mazur  10676739800  140051.58 PLN
49998  MAGDALENA             nowak   77155613090  139931.79 PLN
49999     mateusz        Piotrowski  48103220418   99331.52 USD

[50000 rows x 4 columns]

In [5]:
kopia2 = df

In [6]:
# usunięcie pustych rekordów z DataFrame
df = kopia2
df = df.dropna()
df

             imie          nazwisko        PESEL roczne_zarobki
0           anna         wiśniewski  60457830049  108834.73 USD
1             ewa      Lewandowski   76126262394  114301.11 USD
2           Paweł  WIŚNIEWSKA-NOWAK  18320244397       77021.21
3           KAROL       Lewandowski  45539418997  141116.51 USD
4          OSKAR             Mazur   11623970390   32817.31 EUR
...           ...               ...          ...            ...
49995        anna            Mazur   60969323785  163674.92 USD
49996      Julia     Zielony-Biały   86715437834   87930.15 PLN
49997       Julia             Mazur  10676739800  140051.58 PLN
49998  MAGDALENA             nowak   77155613090  139931.79 PLN
49999     mateusz        Piotrowski  48103220418   99331.52 USD

[49538 rows x 4 columns]

In [7]:
# definicje dodatkowych funkcji

def popraw(arg:str):
    arg = f'{arg}'
    arg = arg.replace(' ','')
    arg = arg.capitalize()
    return arg

def popraw_n(arg:str):
    arg = f'{arg}'
    frag = arg.split('-')
    if len(frag) > 1:
        return f'{popraw(frag[0])}-{popraw(frag[1])}'
    else:
        return popraw(arg)

def PESEL(arg):
    arg = f'{arg}'
    if len(arg) != 11:
        return None
    else:
        return arg

# def popraw(arg:str):
#     arg = f'{arg}'
#     return arg.replace(' ','').title()

In [8]:
# dostosowanie wielkości liter w kolumnie "imie" do formatu "Imię" (pierwsza litera wielka, reszta małe)
df = kopia2
df['imie'] = df['imie'].apply(popraw)
df['nazwisko'] = df['nazwisko'].apply(popraw_n)
df

            imie          nazwisko        PESEL roczne_zarobki
0           Anna        Wiśniewski  60457830049  108834.73 USD
1            Ewa       Lewandowski  76126262394  114301.11 USD
2          Paweł  Wiśniewska-Nowak  18320244397       77021.21
3          Karol       Lewandowski  45539418997  141116.51 USD
4          Oskar             Mazur  11623970390   32817.31 EUR
...          ...               ...          ...            ...
49995       Anna             Mazur  60969323785  163674.92 USD
49996      Julia     Zielony-Biały  86715437834   87930.15 PLN
49997      Julia             Mazur  10676739800  140051.58 PLN
49998  Magdalena             Nowak  77155613090  139931.79 PLN
49999    Mateusz        Piotrowski  48103220418   99331.52 USD

[50000 rows x 4 columns]

In [9]:
# walidacja nr PESEL

df['PESEL'] = df['PESEL'].apply(PESEL)
df

            imie          nazwisko        PESEL roczne_zarobki
0           Anna        Wiśniewski  60457830049  108834.73 USD
1            Ewa       Lewandowski  76126262394  114301.11 USD
2          Paweł  Wiśniewska-Nowak  18320244397       77021.21
3          Karol       Lewandowski  45539418997  141116.51 USD
4          Oskar             Mazur  11623970390   32817.31 EUR
...          ...               ...          ...            ...
49995       Anna             Mazur  60969323785  163674.92 USD
49996      Julia     Zielony-Biały  86715437834   87930.15 PLN
49997      Julia             Mazur  10676739800  140051.58 PLN
49998  Magdalena             Nowak  77155613090  139931.79 PLN
49999    Mateusz        Piotrowski  48103220418   99331.52 USD

[50000 rows x 4 columns]

### Przetwarzanie danych finansowych  

Pole roczne_zarobki zawiera kwotę oraz walutę. Występują różne formaty liczb (kropka lub przecinek jako separator dziesiętny).

**Dodanie kolumny kod_kraju**  
- Na podstawie waluty dodaj nową kolumnę:  
   - Waluta → Kraj  
   - PLN	→ POL  
   - USD	→ USA  
   - EUR	→ GER  

**Konwersja zarobków do jednej waluty (PLN)** 
- Zamień przecinek na kropkę, jeśli występuje.
- Wyodrębnij walutę (PLN, USD, EUR).
- Jeśli waluta nie występuje → przyjmij, że jest to PLN.
- Przelicz wszystkie kwoty na PLN według ustalonych kursów (stan na 5.03.2026 r.):
    - 1 USD = przyjęty kurs 3.677 PLN
    - 1 EUR = przyjęty kurs 4.268 PLN
    - PLN pozostaje bez zmian

Wynik zapisz w nowej kolumnie, np. zarobki_PLN.

In [15]:
# dodatkowe funkcje
def nowa_k(arg):
    arg = f'{arg}'
    last = arg[-3:]

    if last == 'PLN':
        return 'POL'
    elif last == 'USD':
        return 'USA'
    elif last == 'EUR':
        return 'GER'
    else:
        return 'POL'
    
def val(arg):
    arg = f'{arg}'
    arg = arg.replace(',','.')
    arg = arg.replace(' ','')
    waluta = arg[-3:]
    mn = 1
    if waluta == 'USD':
        mn = 3.677
    elif waluta == 'EUR':
        mn = 4.268
   

    try:
        return mn * float(arg)
    except:
        try:
            return mn * float(arg[:-3])
        except:
            return float(0)

In [14]:
# dodanie kolumny kod_kraju na podstawie waluty (np. "PLN" -> "POL", "USD" -> "USA", "EUR" -> "GER")
df['kod_kraju'] = df['roczne_zarobki'].apply(nowa_k)
df

            imie          nazwisko        PESEL roczne_zarobki kod_kraju
0           Anna        Wiśniewski  60457830049  108834.73 USD       USA
1            Ewa       Lewandowski  76126262394  114301.11 USD       USA
2          Paweł  Wiśniewska-Nowak  18320244397       77021.21       POL
3          Karol       Lewandowski  45539418997  141116.51 USD       USA
4          Oskar             Mazur  11623970390   32817.31 EUR       GER
...          ...               ...          ...            ...       ...
49995       Anna             Mazur  60969323785  163674.92 USD       USA
49996      Julia     Zielony-Biały  86715437834   87930.15 PLN       POL
49997      Julia             Mazur  10676739800  140051.58 PLN       POL
49998  Magdalena             Nowak  77155613090  139931.79 PLN       POL
49999    Mateusz        Piotrowski  48103220418   99331.52 USD       USA

[50000 rows x 5 columns]

In [16]:
# przetworzenie kolumny roczne_zarobki, usunięcie symbolu waluty i konwersja na typ numeryczny

df['roczne_zarobki'] = df['roczne_zarobki'].apply(val)

In [17]:
df

            imie          nazwisko        PESEL  roczne_zarobki kod_kraju
0           Anna        Wiśniewski  60457830049    400185.30221       USA
1            Ewa       Lewandowski  76126262394    420285.18147       USA
2          Paweł  Wiśniewska-Nowak  18320244397     77021.21000       POL
3          Karol       Lewandowski  45539418997    518885.40727       USA
4          Oskar             Mazur  11623970390    140064.27908       GER
...          ...               ...          ...             ...       ...
49995       Anna             Mazur  60969323785    601832.68084       USA
49996      Julia     Zielony-Biały  86715437834     87930.15000       POL
49997      Julia             Mazur  10676739800    140051.58000       POL
49998  Magdalena             Nowak  77155613090    139931.79000       POL
49999    Mateusz        Piotrowski  48103220418    365241.99904       USA

[50000 rows x 5 columns]

In [ ]:
# ...
df

In [ ]:
# ...

### Analiza danych
Po oczyszczeniu i przetworzeniu danych wykonaj następujące analizy:

**Selekcja kolumn**

Utwórz nowy zbiór danych zawierający tylko: 
- imię
- nazwisko
- zarobki_PLN

**Liczba osób zarabiających powyżej 300 000 PLN** 
Wyświetl rekordy w których wartość zarobki_PLN > 300 000. Policz ile jest takich rekordów

**Średnie zarobki w podziale na kraj**
Oblicz średnią wartość zarobki_PLN dla każdego kraju (POL, USA, GER). Wypisz wyniki dla każdego kraju osobno.

In [19]:
# selekcja kolumn

nowy = df[['imie','nazwisko','roczne_zarobki']]
nowy

            imie          nazwisko  roczne_zarobki
0           Anna        Wiśniewski    400185.30221
1            Ewa       Lewandowski    420285.18147
2          Paweł  Wiśniewska-Nowak     77021.21000
3          Karol       Lewandowski    518885.40727
4          Oskar             Mazur    140064.27908
...          ...               ...             ...
49995       Anna             Mazur    601832.68084
49996      Julia     Zielony-Biały     87930.15000
49997      Julia             Mazur    140051.58000
49998  Magdalena             Nowak    139931.79000
49999    Mateusz        Piotrowski    365241.99904

[50000 rows x 3 columns]

In [23]:
# liczba osób zarabiających więcej niż 100000 PLN rocznie
print(df[df['roczne_zarobki']>300_000])
print(df[df['roczne_zarobki']>300_000]['roczne_zarobki'].count())

            imie       nazwisko        PESEL  roczne_zarobki kod_kraju
0           Anna     Wiśniewski  60457830049    400185.30221       USA
1            Ewa    Lewandowski  76126262394    420285.18147       USA
3          Karol    Lewandowski  45539418997    518885.40727       USA
8          Paweł     Piotrowski  95714884282    946098.48608       GER
9      Katarzyna       Krawczyk  88275117630    754793.06848       GER
...          ...            ...          ...             ...       ...
49990      Julia  Zielony-Biały  49755308873    450533.32334       USA
49991      Zofia       Krawczyk  52902446441    984522.30844       GER
49994        Jan      Grabowski  24679541527    860695.17226       USA
49995       Anna          Mazur  60969323785    601832.68084       USA
49999    Mateusz     Piotrowski  48103220418    365241.99904       USA

[22255 rows x 5 columns]
22255

In [26]:
# średnie zarobki w poszczególnych krajach
print(df[df['kod_kraju']=='POL']['roczne_zarobki'].mean())
print(df[df['kod_kraju']=='GER']['roczne_zarobki'].mean())
print(df[df['kod_kraju']=='USA']['roczne_zarobki'].mean())

134827.00663493172
572224.1996631382
497118.91698694293

### Pomoc

Metody które mogą być pomocne:
- DataFrame/Pandas:
    - read_csv
    - head
    - info
    - describe
    - min
    - mean
    - count
    - max
    - apply
    - dropna
    - drop(columns=[...])
- string:
    - strip (usuwa spacje)
    - title (zmienia każdy wyraz na pierwszą wielką literę, pozostałe małe litery)
    - capitalize (zmienia na wielką pierwszą literę, pozostałe małe litery)
    - split (rozdziela tekst na wyrazy względem jakiegoś separatora)
    - replace("stary","nowy") - zamienia teksty/litery

### Przykłady na obiekcie o nazwie df:

```python
# example 1
df[df['nazwa_koumny'] == 'wartosc']

# example 2
print(df[df['nazwa_koumny'] == 'wartosc']['nazwa_koumny'].mean())
print(df[df['nazwa_koumny'] > wartosc]['nazwa_koumny'].count())

# example 3
def jakas_funkcja(val):
    #instrukcje zmieniające dane w wartościach komórki...
    ...
    return ... #jakas nowa wartosc


df['nowa_kolumna'] = df['stara_kolumna'].apply(jakas_funkcja)

# example 4
nowa_df = df[['col1','col2','col3']]


# example 5

nowa_df = df.drop(columns=['col1','col2'], axis=1)

# example 6
df = df.dropna()

```